{
  "hash": "ad4136a50ed6588911201aedc4decd68",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 11: Modelling penguins\"\nsubtitle: \"Suggested answers\"\ncategories: \n  - Application exercise\n  - Answers\nfig-width: 7\nfig-asp: 0.618\n---\n\n\n\nIn this application exercise we will be studying penguins.\nThe data can be found in the **palmerpenguins** package and we will use **tidyverse** and **tidymodels** for data exploration and modeling, respectively.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\n```\n:::\n\n\n\nPlease read the following context and take a `glimpse` at the data set before we get started.\n\n> This data set comprising various measurements of three different penguin species, namely Adelie, Gentoo, and Chinstrap.\n> The rigorous study was conducted in the islands of the Palmer Archipelago, Antarctica.\n> These data were collected from 2007 to 2009 by Dr. Kristen Gorman with the Palmer Station Long Term Ecological Research Program, part of the US Long Term Ecological Research Network.\n> The data set is called `penguins`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\n\nOur goal is to understand better how various body measurements and attributes of penguins relate to their body mass.\nFirst, we are going to investigate the relationship between a penguins' flipper lengths and their body masses.\n\n-   **Question:** Based on our research focus, which variable is the response variable?\n\nBody mass.\n\n-   **Demo:** Visualize the relationship between flipper length and body mass of penguins.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-11-modeling-penguins-A_files/figure-html/plot-bm-fl-1.png){width=672}\n:::\n:::\n\n\n\n# Correlation\n\n-   **Your turn (5 minutes):**\n    -   What is correlation?\n        What values can correlation take?\n\n        *Strength and direction of a linear relationship. It's bounded by -1 and 1.*\n\n    -   Are you good at guessing correlation?\n        Give it a try!\n        <https://www.rossmanchance.com/applets/2021/guesscorrelation/GuessCorrelation.html>\n-   **Demo:** What is the correlation between flipper length and body mass of penguins?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# option 1\npenguins |>\n  summarize(r = cor(flipper_length_mm, body_mass_g, use = \"complete.obs\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.871\n```\n\n\n:::\n\n```{.r .cell-code}\n# option 2\npenguins |>\n  drop_na(flipper_length_mm, body_mass_g) |>\n  summarize(r = cor(flipper_length_mm, body_mass_g))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      r\n  <dbl>\n1 0.871\n```\n\n\n:::\n:::\n\n\n\n# Defining, fitting, and summarizing a model\n\n-   **Demo:** Write the population model below that explains the relationship between body mass and flipper length.\n\n$$\nbody~mass = \\beta_0 + \\beta_1 \\times flipper~length + \\epsilon\n$$\n\n-   **Demo:** Fit the linear regression model and display the results. Write the estimated model output below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm, data = penguins)\n\ntidy(bm_fl_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term              estimate std.error statistic   p.value\n  <chr>                <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        -5781.     306.       -18.9 5.59e- 55\n2 flipper_length_mm     49.7      1.52      32.7 4.37e-107\n```\n\n\n:::\n:::\n\n\n\n$$\n\\widehat{body~mass} = -5781 + 49.7 \\times flipper~length\n$$\n\n-   **Your turn:** Interpret the slope and the intercept in the context of the data.\n\n    -   Intercept: Penguins with 0 flipper length are expected, on average, to weigh 5,781 grams.\n\n    -   Slopes: For each additional millimeter of a penguin;s flipper length, the weight of their penguin is expected to be higher, on average, by 49.7 grams.\n\n-   **Your turn:** Recreate the visualization from above, this time adding a regression line to the visualization `geom_smooth(method = \"lm\")`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-11-modeling-penguins-A_files/figure-html/plot-bm-fl-line-1.png){width=672}\n:::\n:::\n\n\n\n-   **Your turn:** What is the estimated body mass for a penguin with a flipper length of 210?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_fit |>\n  predict(new_data = tibble(flipper_length_mm = 210))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4653.\n```\n\n\n:::\n:::\n\n\n\n-   **Demo:** What is the estimated body mass for a penguin with a flipper length of 100?\n\nBut we shouldn't do this prediction based on this model since 100 mm is outside of the range of the data (extrapolation).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_fit |>\n  predict(new_data = tibble(flipper_length_mm = 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 -812.\n```\n\n\n:::\n:::\n\n\n\n# Another model\n\n-   **Demo:** A different researcher wants to look at body weight of penguins based on the island they were recorded on. How are the variables involved in this analysis different?\n\nPredictor is categorical.\n\n-   **Demo:** Make an appropriate visualization to investigate this relationship below. Additionally, calculate the mean body mass by island.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) +\n  geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-11-modeling-penguins-A_files/figure-html/plot-bm-island-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(island) |>\n  summarize(mean_bm = mean(body_mass_g, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  island    mean_bm\n  <fct>       <dbl>\n1 Biscoe      4716.\n2 Dream       3713.\n3 Torgersen   3706.\n```\n\n\n:::\n:::\n\n\n\n-   **Demo:** Change the geom of your previous plot to `geom_point()`. Use this plot to think about how R models these data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) +\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-11-modeling-penguins-A_files/figure-html/plot-bm-island-points-1.png){width=672}\n:::\n:::\n\n\n\n-   **Your turn:** Fit the linear regression model and display the results. Write the estimated model output below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ island, data = penguins)\n\ntidy(bm_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n\n\n:::\n:::\n\n\n\n-   **Demo:** Interpret each coefficient in context of the problem.\n\n    -   Intercept: Penguins from Biscoe island are expected to weigh, on average, 4,716 grams.\n\n    -   Slopes:\n\n        -   Penguins from Dream island are expected to weigh, on average, 1,003 grams less than those from Biscoe island.\n\n        -   Penguins from Torgersen island are expected to weigh, on average, 1,010 grams less than those from Biscoe island.\n\n-   **Demo:** What is the estimated body weight of a penguin on Biscoe island?\n    What are the estimated body weights of penguins on Dream and Torgersen islands?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_island_fit |>\n  predict(new_data = tibble(island = c(\"Biscoe\", \"Dream\", \"Torgersen\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  .pred\n  <dbl>\n1 4716.\n2 3713.\n3 3706.\n```\n\n\n:::\n:::\n",
    "supporting": [
      "ae-11-modeling-penguins-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}