{
  "hash": "fe3b8fc0a3c72a0cbbba63fb7486c2c5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exam 2 Review\"\nformat:\n  html: default\n  pdf: default\nexecute:\n  echo: false\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n:::\n\n\n::: callout-note\nSuggested answers can be found [here](/exam-review/exam-2-review-A.qmd), but resist the urge to peek before you go through it yourself.\n:::\n\n# Part 1 - Employment\n\nA large university knows that about 70% of the full-time students are employed at least 5 hours per week.\nThe members of the Statistics Department wonder if the same proportion of their students work at least 5 hours per week.\nThey randomly sample 25 majors and find that 15 of the students (60%) work 5 or more hours each week.\n\n## Question 1\n\nDescribe how you can set up a simulation to estimate the proportion of statistics majors who work 5 or more hours each week based on this sample.\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n## Question 2\n\nA bootstrap distribution with 1000 simulations is shown below.\nApproximate the bounds of the 95% confidence interval based on this distribution.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](exam-2-review_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Question 3\n\nSuppose the lower bound of the confidence interval from the previous question is L and the upper bound is U.\nWhich of the following is correct?\n\na\\.\nBetween L to U of statistics majors work at least 5 hours per week.\n\nb\\.\n95% of the time the true proportion of statistics majors who work at least 5 hours per week is between L and U.\n\nc\\.\nBetween L and U of random samples of 25 statistics majors are expected to yield confidence intervals that contain the true proportion of statistics majors who work at least 5 hours per week.\n\nd\\.\n95% of random samples of 25 statistics majors will yield confidence intervals between L and U.\n\ne\\.\nNone of the above.\n\n\n{{< pagebreak >}}\n\n\n\n# Part 2 - Blizzard\n\n\n::: {.cell}\n\n:::\n\n\nIn 2020, employees of Blizzard Entertainment circulated a spreadsheet to anonymously share salaries and recent pay increases amidst rising tension in the video game industry over wage disparities and executive compensation.\n(Source: [Blizzard Workers Share Salaries in Revolt Over Pay](https://www.bloomberg.com/news/articles/2020-08-03/blizzard-workers-share-salaries-in-revolt-over-wage-disparities))\n\nThe name of the data frame used for this analysis is `blizzard_salary` and the variables are:\n\n-   `percent_incr`: Raise given in July 2020, as percent increase with values ranging from 1 (1% increase to 21.5 (21.5% increase)\n\n-   `salary_type`: Type of salary, with levels `Hourly` and `Salaried`\n\n-   `annual_salary`: Annual salary, in USD, with values ranging from \\$50,939 to \\$216,856.\n\n-   `performance_rating`: Most recent review performance rating, with levels `Poor`, `Successful`, `High`, and `Top`.\n    The `Poor` level is the lowest rating and the `Top` level is the highest rating.\n\nThe top ten rows of `blizzard_salary` are shown below:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 409 × 4\n   percent_incr salary_type annual_salary performance_rating\n          <dbl> <chr>               <dbl> <chr>             \n 1          1   Salaried               1  High              \n 2          1   Salaried               1  Successful        \n 3          1   Salaried               1  High              \n 4          1   Hourly             33987. Successful        \n 5         NA   Hourly             34798. High              \n 6         NA   Hourly             35360  <NA>              \n 7         NA   Hourly             37440  <NA>              \n 8          0   Hourly             37814. <NA>              \n 9          4   Hourly             41101. Top               \n10          1.2 Hourly             42328  <NA>              \n# ℹ 399 more rows\n```\n\n\n:::\n:::\n\n\n## Question 4\n\nNext, you fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`).\nWe'll call this model `raise_1_fit`.\nA tidy output of the model is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term           estimate  std.error statistic   p.value\n  <chr>             <dbl>      <dbl>     <dbl>     <dbl>\n1 (Intercept)   1.87      0.432           4.33 0.0000194\n2 annual_salary 0.0000155 0.00000452      3.43 0.000669 \n```\n\n\n:::\n:::\n\n\nWhich of the following is the best interpretation of the slope coefficient?\n\na.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.55%.\nb.  For every additional \\$1,000 of annual salary, the raise goes up by 0.0155%.\nc.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 0.0155%.\nd.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.87%.\n\n## Question 5\n\nYou then fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`) and performance ratings (`performance_rating`).\nWe'll call this model `raise_2_fit`.\nWhich of the following is definitely true based on the information you have so far?\n\na.  Intercept of `raise_2_fit` is higher than intercept of `raise_1_fit`.\nb.  Slope of `raise_2_fit` is higher than RMSE of `raise_1_fit`.\nc.  Adjusted $R^2$ of `raise_2_fit` is higher than adjusted $R^2$ of `raise_1_fit`.\nd.  $R^2$ of `raise_2_fit` is higher $R^2$ of `raise_1_fit`.\n\n## Question 6\n\nThe tidy model output for the `raise_2_fit` model you fit is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                            estimate  std.error statistic  p.value\n  <chr>                              <dbl>      <dbl>     <dbl>    <dbl>\n1 (Intercept)                   3.55       0.508           6.99 1.99e-11\n2 annual_salary                 0.00000989 0.00000436      2.27 2.42e- 2\n3 performance_ratingPoor       -4.06       1.42           -2.86 4.58e- 3\n4 performance_ratingSuccessful -2.40       0.397          -6.05 4.68e- 9\n5 performance_ratingTop         2.99       0.715           4.18 3.92e- 5\n```\n\n\n:::\n:::\n\n\nWhen your teammate sees this model output, they remark \"The coefficient for `performance_ratingSuccessful` is negative, that's weird. I guess it means that people who get successful performance ratings get lower raises.\" How would you respond to your teammate?\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n## Question 7\n\nUltimately, your teammate decides they don't like the negative slope coefficients in the model output you created (not that there's anything wrong with negative slope coefficients!), does something else, and comes up with the following model output.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                            estimate  std.error statistic    p.value\n  <chr>                              <dbl>      <dbl>     <dbl>      <dbl>\n1 (Intercept)                  -0.511      1.47          -0.347 0.729     \n2 annual_salary                 0.00000989 0.00000436     2.27  0.0242    \n3 performance_ratingSuccessful  1.66       1.42           1.17  0.242     \n4 performance_ratingHigh        4.06       1.42           2.86  0.00458   \n5 performance_ratingTop         7.05       1.53           4.60  0.00000644\n```\n\n\n:::\n:::\n\n\nUnfortunately they didn't write their code in a Quarto document, instead just wrote some code in the Console and then lost track of their work.\nThey remember using the `fct_relevel()` function and doing something like the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblizzard_salary <- blizzard_salary |>\n  mutate(performance_rating = fct_relevel(performance_rating, ___))\n```\n:::\n\n\nWhat should they put in the blanks to get the same model output as above?\n\na.  \"Poor\", \"Successful\", \"High\", \"Top\"\nb.  \"Successful\", \"High\", \"Top\"\nc.  \"Top\", \"High\", \"Successful\", \"Poor\"\nd.  Poor, Successful, High, Top\n\n## Question 8\n\nSuppose we fit a model to predict `percent_incr` from `annual_salary` and `salary_type`.\nA tidy output of the model is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term                 estimate  std.error statistic p.value\n  <chr>                   <dbl>      <dbl>     <dbl>   <dbl>\n1 (Intercept)         1.24      0.570           2.18 0.0300 \n2 annual_salary       0.0000137 0.00000464      2.96 0.00329\n3 salary_typeSalaried 0.913     0.544           1.68 0.0938 \n```\n\n\n:::\n:::\n\n\nWhich of the following visualizations represent this model?\nExplain your reasoning.\n\n\n::: {#fig-raise-salary-type .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Option 1](exam-2-review_files/figure-html/fig-raise-salary-type-1.png){#fig-raise-salary-type-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 2](exam-2-review_files/figure-html/fig-raise-salary-type-2.png){#fig-raise-salary-type-2 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 3](exam-2-review_files/figure-html/fig-raise-salary-type-3.png){#fig-raise-salary-type-3 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 4](exam-2-review_files/figure-html/fig-raise-salary-type-4.png){#fig-raise-salary-type-4 width=672}\n:::\n\nVisualizations of the relationship between percent increase, annual\nsalary, and salary type\n\n:::\n\n\n::: {.content-visible when-format=\"pdf\"}\n\n{{< pagebreak >}}\n\n\n:::\n\n## Question 9\n\nDefine the term parsimonious model.\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n\n{{< pagebreak >}}\n\n\n\n## Question 10\n\nSuppose you now fit a model to predict the natural log of percent increase, `log(percent_incr)`, from performance rating.\nThe model is called `raise_4_fit`.\n\n\n::: {.cell}\n\n:::\n\n\nYou're provided the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(raise_4_fit) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term                         estimate exp_estimate\n  <chr>                           <dbl>        <dbl>\n1 (Intercept)                     -7.15     0.000786\n2 performance_ratingSuccessful     6.93  1025.      \n3 performance_ratingHigh           8.17  3534.      \n4 performance_ratingTop            8.91  7438.      \n```\n\n\n:::\n:::\n\n\nBased on this, which of the following is true?\n\na\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by 10.25% compared to the employees with Poor performance rating.\n\nb\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by 6.93% compared to the employees with Poor performance rating.\n\nc\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 1025 compared to the employees with Poor performance rating.\n\nd\\.\nThe model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 6.93 compared to the employees with Poor performance rating.\n\n# Part 3 - Miscellaneous\n\n## Question 11\n\nWhich of the following is the definiton of a regression model?\nSelect all that apply.\n\na\\.\n$\\hat{y} = \\beta_0 + \\beta_1 X_1$\n\nb\\.\n$y = \\beta_0 + \\beta_1 X_1$\n\nc\\.\n$\\hat{y} = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\nd\\.\n$y = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\n## Question 12\n\n**Choose the best answer.**\n\nA survey based on a random sample of 2,045 American teenagers found that a 95% confidence interval for the mean number of texts sent per month was (1450, 1550).\nA valid interpretation of this interval is\n\na.  95% of all teens who text send between 1450 and 1550 text messages per month.\nb.  If a new survey with the same sample size were to be taken, there is a 95% chance that the mean number of texts in the sample would be between 1450 and 1550.\nc.  We are 95% confident that the mean number of texts per month of all American teens is between 1450 and 1550.\nd.  We are 95% confident that, were we to repeat this survey, the mean number of texts per month of those taking part in the survey would be between 1450 and 1550.\n\n\n{{< pagebreak >}}\n\n\n\n## Bonus\n\nPick a concept we introduced in class so far that you've been struggling with and explain it in your own words.\n",
    "supporting": [
      "exam-2-review_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}