---
title: "Visualizing various types of data"
subtitle: "Lecture 3"
date: "January 23, 2024"
format: revealjs
---

# Warm up

```{r}
#| echo: false

library(countdown)
ggplot2::theme_set(ggplot2::theme_gray(base_size = 16))
```

## While you wait...

**Questions from the prepare materials?**

```{=html}
<iframe allowfullscreen frameborder="0" height="100%" mozallowfullscreen style="min-width: 500px; min-height: 355px" src="https://app.wooclap.com/STA199S24?from=status-bar?" width="100%"></iframe>
```
## Questions from last time {.smaller}

-   ...

## Announcements

-   ...

# From last time

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)
```

## Violin plots

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-1
#| fig-show: hide
#| code-line-numbers: "|4|5|8"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g
    )
  ) +
  geom_violin()
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-1
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::

## Multiple geoms

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-2
#| fig-show: hide
#| code-line-numbers: "9"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g
    )
  ) +
  geom_violin() +
  geom_point()
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-2
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::

## Multiple geoms

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-3
#| fig-show: hide
#| code-line-numbers: "9"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g
    )
  ) +
  geom_violin() +
  geom_jitter()
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-3
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::

## Multiple geoms + aesthetics

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-4
#| fig-show: hide
#| code-line-numbers: "6"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g,
    color = species
    )
  ) +
  geom_violin() +
  geom_jitter()
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-4
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::

## Multiple geoms + aesthetics

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-5
#| fig-show: hide
#| code-line-numbers: "11-13"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g,
    color = species
    )
  ) +
  geom_violin() +
  geom_jitter() +
  theme(
    legend.position = "none"
  )
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-5
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::

## Multiple geoms + aesthetics

::: columns
::: {.column width="50%"}
```{r}
#| label: penguins-violin-6
#| fig-show: hide
#| code-line-numbers: "14"

ggplot(
  penguins,
  aes(
    x = species,
    y = body_mass_g,
    color = species
    )
  ) +
  geom_violin() +
  geom_jitter() +
  theme(
    legend.position = "none"
  ) +
  scale_color_colorblind()
```
:::

::: {.column width="50%"}
```{r}
#| ref.label: penguins-violin-6
#| echo: false
#| fig-width: 5
#| fig-asp: 0.8
```
:::
:::
