---
title: "Linear regression with a multiple predictors II"
subtitle: "Lecture 17"
date: "March 21, 2024"
format: 
  revealjs:
    footer: "[🔗 sta199-s24.github.io](https://sta199-s24.github.io/) &nbsp;·&nbsp; [❓ Ask on Ed](https://edstem.org/us/courses/50730)"
---

# Warm up

```{r}
#| echo: false
#| message: false
library(countdown)
library(tidyverse)
ggplot2::theme_set(theme_gray(base_size = 16))
```

## While you wait for class to begin...

::: nonincremental
Any questions from prepare materials?
:::

```{=html}
<iframe allowfullscreen frameborder="0" height="100%" mozallowfullscreen style="min-width: 500px; min-height: 355px" src="https://app.wooclap.com/STA199S24?from=status-bar?" width="100%"></iframe>
```
## Project proposals

::: task
Any questions?
:::

# From last time

## Application exercise: `ae-12-modeling-penguins-multi` {.smaller}

::: appex
Continue work on `ae-12-modeling-penguins-multi.qmd`.
:::

**Goals:**

-   Recap modeling with a single predictor
-   Fit and interpret models with multiple predictors
-   Distinguish between additive and interaction models

# Model selection and overfitting

## Goals

-   Review prediction and interpretation of model results
-   Review main and interaction effects models
-   Discuss model selection further

## Application exercise: `ae-13-modeling-loans` {.smaller}

::: appex
-   Go to your project called `ae`.
-   If there are any uncommitted files, commit them, and push.
-   Work on `ae-13-modeling-loans.qmd`.
:::
