---
title: "Welcome to STA 199"
subtitle: "Lecture 0"
date: "January 11, 2024"
format: revealjs
---

# From last time...

## Course homepage

Let's take a tour!

## Collaboration policy

-   Only work that is clearly assigned as team work should be completed collaboratively.

-   Homeworks must be completed individually. You may **not** directly share answers / code with others, however you are welcome to discuss the problems in general and ask for advice.

-   Exams must be completed individually. You may **not** discuss any aspect of the exam with peers. If you have questions, post as private questions on the course forum, only the teaching team will see and answer.

## Sharing / reusing code policy

-   We are aware that a huge volume of code is available on the web, and many tasks may have solutions posted

-   Unless explicitly stated otherwise, this course's policy is that you may make use of any online resources (e.g. RStudio Community, StackOverflow, etc.) but you must explicitly cite where you obtained any code you directly use or use as inspiration in your solution(s).

-   Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism, regardless of source

## Use of generative AI {.smaller}

-   Treat generative AI, such as ChatGPT, the same as other online resources.

-   Guiding principles:

    -   \(1\) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate—rather than hinder—learning.

    -   \(2\) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

-   **✅ AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. See the syllabus for guidelines for citing AI-generated content.

-   **❌ AI tools for narrative:** Unless instructed otherwise, you may not use generative AI to write narrative on assignments. In general, you may use generative AI as a resource as you complete assignments but not to answer the exercises for you.

## Academic integrity

> To uphold the Duke Community Standard:
>
> -   I will not lie, cheat, or steal in my academic endeavors;
>
> -   I will conduct myself honorably in all my endeavors; and
>
> -   I will act if the Standard is compromised.

## Most importantly!

Ask if you're not sure if something violates a policy!

# next