{
  "hash": "f0e6e33d6cf3aac721558e0ad7f257b0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 15: Modeling houses in Duke Forest\"\nsubtitle: \"Suggested answers\"\ncategories: \n  - Application exercise\n  - Answers\neditor_options: \n  chunk_output_type: console\n---\n\n\n\nIn this application exercise, we will\n\n-   use bootstrapping to quantify the uncertainty around a measure of center – median\n-   use bootstrapping to quantify the uncertainty around a measure of relationship – slope\n-   interpret confidence intervals\n\nThe dataset are on housing prices in Duke Forest – a dataset you've seen before!\nIt's called `duke_forest` and it's in the **openintro** package.\nAdditionally, we'll use **tidyverse** and **tidymodels** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\n```\n:::\n\n\n\n# Typical size of a house in Duke Forest\n\n## Exercise 1\n\nVisualize the distribution of sizes of houses in Duke Forest.\nWhat is the size of a typical house?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(duke_forest, aes(x = area)) +\n  geom_histogram(binwidth = 250)\n```\n\n::: {.cell-output-display}\n![](ae-15-duke-forest-bootstrap-A_files/figure-html/df-area-hist-1.png){width=672}\n:::\n:::\n\n\n\n## Exercise 2\n\nConstruct a 95% confidence interval for the typical size of a house in Duke Forest.\nInterpret the interval in context of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\ndf_araa_median_boot <- duke_forest |>\n  specify(response = area) |>\n  generate(reps = 100, type = \"bootstrap\") |>\n  calculate(stat = \"median\")\n\nggplot(df_araa_median_boot, aes(x = stat)) +\n  geom_histogram(binwidth = 50)\n```\n\n::: {.cell-output-display}\n![](ae-15-duke-forest-bootstrap-A_files/figure-html/df-area-median-boot-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndf_araa_median_boot |>\n  summarize(\n    l = quantile(stat, 0.025),\n    u = quantile(stat, 0.975)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n      l     u\n  <dbl> <dbl>\n1 2365. 2836.\n```\n\n\n:::\n:::\n\n\n\n*We are 95% confident that the median house in Duke Forest is between 2,365 and 2,836 square feet.*\n\n## Exercise 3\n\nWithout calculating it – would a 90% confidence interval be wider or narrower?\nWhy?\n\n*Narrower, lower confidence level needed so we can be more precise.*\n\n## Exercise 4\n\nConstruct the 90% confidence interval and interpret it.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_araa_median_boot |>\n  summarize(\n    l = quantile(stat, 0.05),\n    u = quantile(stat, 0.95)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n      l     u\n  <dbl> <dbl>\n1 2395.  2830\n```\n\n\n:::\n:::\n\n\n\n*We are 95% confident that the median house in Duke Forest is between 2,395 and 2,830 square feet.*\n\n# Relationship between price and size\n\nThe following model predicts price of a house in Duke Forest from its size.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_price_area_fit <- linear_reg() |>\n  fit(price ~ area, data = duke_forest)\n\ntidy(df_price_area_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  116652.   53302.       2.19 3.11e- 2\n2 area            159.      18.2      8.78 6.29e-14\n```\n\n\n:::\n:::\n\n\n\nThe slope can be interpreted as:\n\n> For each additional square feet, the model predicts that prices of houses in Duke Forest are higher by \\$159, on average.\n\n## Exercise 5\n\nQuantify the uncertainty around this slope using a 95% bootstrap confidence interval and interpret the interval in context of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_price_area_boot <- duke_forest |>\n  specify(price ~ area) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"slope\")\n\nggplot(df_price_area_boot, aes(x = stat)) +\n  geom_histogram(binwidth = 10)\n```\n\n::: {.cell-output-display}\n![](ae-15-duke-forest-bootstrap-A_files/figure-html/df-price-area-boot-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndf_price_area_boot |>\n  summarize(\n    l = quantile(stat, 0.025),\n    u = quantile(stat, 0.975)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n      l     u\n  <dbl> <dbl>\n1  89.9  214.\n```\n\n\n:::\n:::\n\n\n\n*We are 95% confident that, for each additional square feet, the model predicts that prices of houses in Duke Forest are higher by \\$89.9 to \\$214, on average.*\n",
    "supporting": [
      "ae-15-duke-forest-bootstrap-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}