---
title: "Write-up and presentation"
subtitle: "Milestone 4"
categories: "Project"
---

# Write-up

## Expectations

Your written report must be completed in the `index.qmd` file and must be reproducible.
All team members should contribute to the GitHub repository, with regular meaningful commits.

Before you finalize your write up, make sure the printing of code chunks is off with the option `echo: false` in the YAML.

The mandatory components of the report are below.
You are free to add additional sections as necessary.
The report, including visualizations, should be no more than 10 pages long (if it were to be printed)**.** There is no minimum page requirement; however, you should comprehensively address all of the analysis in your report.

To check how many pages your report is, open it in your browser and go to File \> Print \> Save as PDF and review the number of pages.

Be selective in what you include in your final write-up.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis.

You are welcome to include an appendix with additional work at the end of the written report document; however, grading will largely be based on the content in the main body of the report.
You should assume the reader will ***not*** see the material in the appendix unless prompted to view it in the main body of the report.
The appendix should be neatly formatted and easy for the reader to navigate.
It is not included in the 10-page limit.

## Components

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.
The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The exploratory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.
It incorporates appropriate visualizations and summary statistics.

### Methodology

This section includes a brief description of your analysis process.
Explain the reasoning for the types of analyses you do, exploratory, inferential, or modeling.
If you've chosen to do inference, make sure to include a justification for why that inferential approach is appropriate.
If you've chosen to do modeling, describe the model(s) you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, interactions considered, variable transformations (if needed), assessment of conditions and diagnostics, and any other relevant considerations that were part of the model fitting process.

#### Grading criteria

The analysis steps are appropriate for the data and research question.
The group used a thorough and careful approach to determine analyses types and addressed any concerns over appropriateness of analyses chosen.

### Results

This is where you will discuss your overall finding and describe the key results from your analysis.
The goal is not to interpret every single element of an output shown, but instead to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The analysis results are clearly assesses and interesting findings from the analysis are described.
Interpretations are used to to support the key findings and conclusions, rather than merely listing, e.g., the interpretation of every model coefficient.

### Discussion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the analysis results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Grading

The write-up is worth 40 points, broken down as follows:

| Total                         | 40 pts |
|-------------------------------|--------|
| **Introduction/data**         | 6 pts  |
| **Methodology**               | 10 pts |
| **Results**                   | 14 pts |
| **Discussion**                | 6 pts  |
| **Organization + formatting** | 4 pts  |

# Presentation + slides {#presentation-slides}

## Slides

In addition to the written report, your team will also create presentation slides and deliver presentation that summarize and showcase your project.
Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.
These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

You can create your slides with any software you like (Keynote, PowerPoint, Google Slides, etc.).
We recommend choosing an option that's easy to collaborate with, e.g., Google Slides.
If you choose this option, save the slides as PDF and upload it to your repo as `presentation.pdf`.

You can also use Quarto to make your slides!
While we won't be covering making slides with Quarto in the class, we would be happy to help you with it in office hours.
It's no different than writing other documents with Quarto, so the learning curve will not be steep!

The slide deck should be roughly 6 content slides + 1 title slide.
Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data
-   Slide 3: Highlights from EDA
-   Slide 4-5: Inference/modeling/other analysis
-   Slide 6: Conclusions + future work

## Presentation

Presentations will take place in class during the last lab of the semester.
**The presentation must be no longer than 5 minutes.** You can choose to present live in class (recommended) or pre-record a video to be shown in class.
Either way you must attend the lab session for the Q&A following your presentation.

If you choose to pre-record your presentation, you may use can use any platform that works best for your group to record your presentation.
Below are a few resources on recording videos:

-   [Recording presentations in Zoom](https://kb.siue.edu/61721)
-   [Apple Quicktime for screen recording](https://support.apple.com/en-gb/guide/quicktime-player/qtp97b08e666/mac)
-   [Windows 10 built-in screen recording functionality](https://www.youtube.com/watch?v=OfPbr1mRDuo)
-   [Kap for screen recording](https://getkap.co/)

Once your video is ready, upload the video to Warpwire or another video platform (e.g., YouTube), then add a link to your video in your repo README.

To upload your video to Warpwire:

-   Click the Warpwire tab in the course Canvas site.
-   Click the "+" and select "Upload files".
-   Locate the video on your computer and click to upload.
-   Once you've uploaded the video to Warpwire, click to share the video and copy the video's URL. You will need this when you post the video in the discussion forum.

## Grading

The presentation is worth 25 points, broken down as follows:

| Total                         | 25 pts |
|-------------------------------|--------|
| **Slides**                    | 10 pts |
| **Presentation**              | 15 pts |

### Slides

Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

### Presentation

- Time management: Did the team divide the time well amongst themselves or got cut off going over time?
- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Did everyone get a chance to say something meaningful about the project?
- Teamwork: Did the team present a unified story, or did it seem like independent pieces of work patched together?
- Creativity and critical thought: Is the project carefully thought out? Does it appear that time and effort went into the planning and implementation of the project?
- Content: Including, but not limited to the following:
  - Is the question well articulated in the presentation?
  - Can the question be answered with the data?
  - Does the analysis answer the question?
  - Are the conclusion(s) made based on the analysis justifiable?
  - Are the limitations carefully considered and articulated?

