{
  "hash": "8f2263c123305a30cc3e2936008587ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 12: Modeling penguins with multiple predictors\"\nsubtitle: \"Suggested answers\"\ncategories: \n  - Application exercise\n  - Answers\neditor: visual\n---\n\n\n\nIn this application exercise we will be studying penguins.\nThe data can be found in the **palmerpenguins** package and we will use **tidyverse** and **tidymodels** for data exploration and modeling, respectively.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\n```\n:::\n\n\n\nPlease read the following context and take a `glimpse` at the data set before we get started.\n\n> This data set comprising various measurements of three different penguin species, namely Adelie, Gentoo, and Chinstrap.\n> The rigorous study was conducted in the islands of the Palmer Archipelago, Antarctica.\n> These data were collected from 2007 to 2009 by Dr. Kristen Gorman with the Palmer Station Long Term Ecological Research Program, part of the US Long Term Ecological Research Network.\n> The data set is called `penguins`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\n\nOur goal is to understand better how various body measurements and attributes of penguins relate to their body mass.\n\n# Body mass vs. flipper length\n\nThe regression model for body mass vs. flipper length is as follows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm, data = penguins)\n\ntidy(bm_fl_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term              estimate std.error statistic   p.value\n  <chr>                <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        -5781.     306.       -18.9 5.59e- 55\n2 flipper_length_mm     49.7      1.52      32.7 4.37e-107\n```\n\n\n:::\n:::\n\n\n\nAnd here is the model visualized:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-modeling-penguins-multi-A_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n-   **Demo:** What is the estimated body mass for a penguin with a flipper length of 210?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_210 <- tibble(flipper_length_mm = 210)\n\npredict(bm_fl_fit, new_data = penguin_210)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4653.\n```\n\n\n:::\n:::\n\n\n\n-   **Your turn:** What is the estimated body mass for a penguin with a flipper length of 100?\n\nBut we shouldn't do this prediction based on this model since 100 mm is outside of the range of the data (extrapolation).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_100 <- tibble(flipper_length_mm = 100)\n\nbm_fl_fit |>\n  predict(new_data = penguin_100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 -812.\n```\n\n\n:::\n:::\n\n\n\n# Body mass vs. island\n\n-   **Demo:** A different researcher wants to look at body weight of penguins based on the island they were recorded on. How are the variables involved in this analysis different?\n\nPredictor is categorical.\n\n-   **Demo:** Make an appropriate visualization to investigate this relationship below. Additionally, calculate the mean body mass by island.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) +\n  geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-modeling-penguins-multi-A_files/figure-html/plot-bm-island-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(island) |>\n  summarize(mean_bm = mean(body_mass_g, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  island    mean_bm\n  <fct>       <dbl>\n1 Biscoe      4716.\n2 Dream       3713.\n3 Torgersen   3706.\n```\n\n\n:::\n:::\n\n\n\n-   **Demo:** Change the geom of your previous plot to `geom_point()`. Use this plot to think about how R models these data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) +\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-modeling-penguins-multi-A_files/figure-html/plot-bm-island-points-1.png){width=672}\n:::\n:::\n\n\n\n-   **Your turn:** Fit the linear regression model and display the results. Write the estimated model output below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ island, data = penguins)\n\ntidy(bm_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n\n\n:::\n:::\n\n\n\n-   **Demo:** Interpret each coefficient in context of the problem.\n\n    -   Intercept: Penguins from Biscoe island are expected to weigh, on average, 4,716 grams.\n\n    -   Slopes:\n\n        -   Penguins from Dream island are expected to weigh, on average, 1,003 grams less than those from Biscoe island.\n\n        -   Penguins from Torgersen island are expected to weigh, on average, 1,010 grams less than those from Biscoe island.\n\n-   **Demo:** What is the estimated body weight of a penguin on Biscoe island?\n    What are the estimated body weights of penguins on Dream and Torgersen islands?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguins <- tibble(island = c(\"Biscoe\", \"Dream\", \"Torgersen\"))\n\npredict(bm_island_fit, new_data = new_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  .pred\n  <dbl>\n1 4716.\n2 3713.\n3 3706.\n```\n\n\n:::\n:::\n\n\n\n# Body mass vs. flipper length and island\n\nNext, we will expand our understanding of models by continuing to learn about penguins.\nSo far, we modeled body mass by flipper length, and in a separate model, modeled body mass by island.\nCould it be possible that the estimated body mass of a penguin changes by both their flipper length AND by the island they are on?\n\n-   **Demo:** Fit a model to predict body mass from flipper length and island. Display the summary output and write out the estimate regression equation below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm + island, data = penguins)\n\ntidy(bm_fl_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        -4625.     392.      -11.8  4.29e-27\n2 flipper_length_mm     44.5      1.87     23.9  1.65e-74\n3 islandDream         -262.      55.0      -4.77 2.75e- 6\n4 islandTorgersen     -185.      70.3      -2.63 8.84e- 3\n```\n\n\n:::\n:::\n\n\n\n$$\n\\widehat{body~mass} = -4625 + 44.5 \\times flipper~length - 262 \\times Dream - 185 \\times Torgersen\n$$\n\n## Additive vs. interaction models\n\n-   **Your turn:** Run the two chunks of code below and create two separate plots. How are the two plots different than each other? Which plot does the model we fit above represent?\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\n# Plot A\nggplot(\n  penguins, \n  aes(x = flipper_length_mm, y = body_mass_g, color = island)\n  ) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Plot A - Interaction model\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-modeling-penguins-multi-A_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot B\nbm_fl_island_aug <- augment(bm_fl_island_fit, new_data = penguins)\nggplot(\n  bm_fl_island_aug, \n  aes(x = flipper_length_mm, y = body_mass_g, color = island)\n  ) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(aes(y = .pred), method = \"lm\") +\n  labs(title = \"Plot B - Additive model\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite values (`stat_smooth()`).\nRemoved 2 rows containing missing values (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-12-modeling-penguins-multi-A_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n\nPlot B represent the model we fit.\n\n-   **Your turn:** Interpret the slope coefficient for flipper length in the context of the data and the research question.\n\nFor every 1 millimeter the flipper is longer, we expect body mass to be higher, on average, by 44.5 grams, holding all else (the island) constant.\nIn other words, this is true for penguins in a given island, regardless of the island.\n\n-   **Demo:** Predict the body mass of a Dream island penguin with a flipper length of 200 mm.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_200_Dream <- tibble(\n  flipper_length_mm = 200,\n  island = \"Dream\"\n)\n\npredict(bm_fl_island_fit, new_data = penguin_200_Dream)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4021.\n```\n\n\n:::\n:::\n\n\n\n-   **Review:** Look back at Plot B. What assumption does the additive model make about the slopes between flipper length and body mass for each of the three islands?\n\nThe additive model assumes the same slope between body mass and flipper length for all three islands.\n\n-   **Demo:** Now fit the interaction model represented in Plot A and write the estimated regression model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_int_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm * island, data = penguins)\n\ntidy(bm_fl_island_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term                              estimate std.error statistic  p.value\n  <chr>                                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                        -5464.     431.      -12.7  2.51e-30\n2 flipper_length_mm                     48.5      2.05     23.7  1.66e-73\n3 islandDream                         3551.     969.        3.66 2.89e- 4\n4 islandTorgersen                     3218.    1680.        1.92 5.62e- 2\n5 flipper_length_mm:islandDream        -19.4      4.94     -3.93 1.03e- 4\n6 flipper_length_mm:islandTorgersen    -17.4      8.73     -1.99 4.69e- 2\n```\n\n\n:::\n:::\n\n\n\n$$\n\\widehat{body~mass} = -5464 \\\\\n+ 48.5 \\times flipper~length \\\\\n+ 3551 \\times Dream + 3218 \\times Torgersen \\\\\n- 19.4 \\times flipper~length*Dream - 17.4 \\times flipper~length*Torgersen\n$$\n\n-   **Review:** What does modeling body mass with an interaction effect get us that without doing so does not?\n\nThe interaction effect allows us to model the rate of change in estimated body mass as flipper length increases as different in the three islands.\n\n-   **Your turn:** Predict the body mass of a Dream island penguin with a flipper length of 200 mm.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(bm_fl_island_int_fit, new_data = penguin_200_Dream)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 3915.\n```\n\n\n:::\n:::\n\n\n\n## Choosing a model\n\nRule of thumb: **Occam's Razor** - Don't overcomplicate the situation!\nWe prefer the *simplest* best model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(bm_fl_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.774         0.772  383.      386. 7.60e-109     3 -2517. 5045. 5064.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(bm_fl_island_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.786         0.783  374.      246. 4.55e-110     5 -2508. 5031. 5057.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n-   **Review:** What is R-squared? What is adjusted R-squared?\n\nR-squared is the percent variability in the response that is explained by our model.\n(Can use when models have same number of variables for model selection)\n\nAdjusted R-squared is similar, but has a penalty for the number of variables in the model.\n(Should use for model selection when models have different numbers of variables).\n\n# Your turn\n\n-   Now, explore body mass, and it's relationship to bill length and flipper length.\n    Brainstorm: How could we visualize this?\n\n-   Fit the additive model.\n    Interpret the slope for flipper in context of the data and the research question.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_bl <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm + bill_length_mm, data = penguins)\n\ntidy(bm_fl_bl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)       -5737.      308.      -18.6  7.80e-54\n2 flipper_length_mm    48.1       2.01     23.9  7.56e-75\n3 bill_length_mm        6.05      5.18      1.17 2.44e- 1\n```\n\n\n:::\n:::\n\n\n\nHolding all other variables constant, for every additional millimeter in flipper length, we expect the body mass of penguins to be higher, on average, by 48.1 grams.\n",
    "supporting": [
      "ae-12-modeling-penguins-multi-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}