{
  "hash": "a972b9bb72652ce489950018cb0cea47",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quantifying uncertainty with bootstrap intervals\"\nsubtitle: \"Lecture 20\"\ndate: \"April 2, 2024\"\nformat: \n  revealjs:\n    footer: \"[🔗 sta199-s24.github.io](https://sta199-s24.github.io/) &nbsp;·&nbsp; [❓ Ask on Ed](https://edstem.org/us/courses/50730)\"\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n# Warm up\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n## While you wait for class to begin...\n\n::: nonincremental\nAny questions from prepare materials?\n:::\n\n\n\n\n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"100%\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/STA199S24?from=status-bar?\" width=\"100%\"></iframe>\n```\n\n\n\n\n## Announcements\n\n-   Lab 7 (last lab) is due Monday 4/8 at 8 am\n-   Have at least one team meeting this week to review feedback and make some progress on your lab for peer review after exam on Monday 4/15\n\n# Quantifying uncertainty\n\n## Case study: Airbnb in Asheville, NC {.smaller}\n\nWe have data on the price per guest (ppg) for a random sample of 50 Airbnb listings in 2020 for Asheville, NC. We are going to use these data to investigate what we would of expected to pay for an Airbnb in in Asheville, NC in June 2020.\n\nWe have data on the price per guest (ppg) for a random sample of 50 Airbnb listings in 2020 for Asheville, NC. We are going to use these data to investigate what we would of expected to pay for an Airbnb in in Asheville, NC in June 2020.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabb <- read_csv(\"data/asheville.csv\")\n\nglimpse(abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 50\nColumns: 1\n$ ppg <dbl> 48.00000, 40.00000, 99.00000, 13.00000, 55.00000, 75.00000, 74.00000, 169.00…\n```\n\n\n:::\n:::\n\n\n\n\n\n## Terminology {.smaller}\n\n-   **Population parameter** - What we are interested in.\n    Statistical measure that describes an entire population.\n\n-   **Sample statistic (point estimate)** - describes a sample.\n    A piece of information you get from a fraction of the population.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabb |> \n  summarize(ppg_mean = mean(ppg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  ppg_mean\n     <dbl>\n1     76.6\n```\n\n\n:::\n:::\n\n\n\n\n\n## Catching a fish\n\n::: task\nSuppose you're fishing in a murky lake.\nAre you more likely to catch a fish using a spear or a net?\n:::\n\n. . .\n\n-   Spear $\\rightarrow$ point estimate\n-   Net $\\rightarrow$ interval estimate\n\n## Constructing confidence intervals\n\nQuantifying the variability of the sample statistics to help calculate a range of plausible values for the population parameter of interest:\n\n-   Via simulation $\\rightarrow$ using bootstrapping -- using a statistical procedure that re samples a single data set to create many simulated samples.\n\n-   Via mathematical formulas $\\rightarrow$ using the Central Limit Theorem\n\n## Bootstrapping, what? {.smaller}\n\n-   The term bootstrapping comes from the phrase \"pulling oneself up by one's bootstraps\", which is a metaphor for accomplishing an impossible task without any outside help.\n\n-   Impossible task: estimating a population parameter using data from only the given sample.\n\n. . .\n\n::: callout-note\nNote: This notion of saying something about a population parameter using only information from an observed sample is the crux of statistical inference, it is not limited to bootstrapping.\n:::\n\n## Bootstrapping, how?\n\n-   Resample with replacement from our data n times, where n is the sample size\n-   Calculate the sample statistic of interest of the new, resampled (bootstrapped) sample and record the value\n-   Do this entire process many many times to build the **bootstrap distribution**\n\n## Bootstrapping Airbnb rentals\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(25) \n\nboot_dist_abb <- abb |>\n  specify(response = ppg) |>\n  generate(reps = 100, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n:::\n\n\n\n\n\n## The bootstrap distribution\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(boot_dist_abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 2\n$ replicate <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,…\n$ stat      <dbl> 73.11500, 78.78333, 80.19333, 83.42000, 70.15000, 73.03667, 76.41333, …\n```\n\n\n:::\n:::\n\n\n\n\n\n## Visualzing the bootstrap distribution {.smaller}\n\n::: task\nWhat do you expect the center of the bootstrap distribution to be?\nWhy?\nCheck your guess by visualizing the distribution.\n:::\n\n. . .\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(boot_dist_abb, aes(x = stat)) + \n  geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/boot-dist-abb-plot-1.png){width=576}\n:::\n:::\n\n\n\n\n\n## Calculating the bootstrap distribution\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_dist_abb |>\n  summarize(\n    lower = quantile(stat, 0.025),\n    upper = quantile(stat, 0.975)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower upper\n  <dbl> <dbl>\n1  64.7  89.6\n```\n\n\n:::\n:::\n\n\n\n\n\n## Interpretation {.smaller}\n\n::: panel-tabset\n### Think\n\n::: task\nWhich of the following is the correct interpretation of the bootstrap interval?\n:::\n\na.  There is a 95% probability the true mean price per guest for an Airbnb in Asheville is between \\$64.7 and \\$89.6.\n\nb.  There is a 95% probability the price per guest for an Airbnb in Asheville in this sample is between \\$64.7 and \\$89.6.\n\nc.  We are 95% confident the true mean price per guest for Airbnbs in Asheville is between \\$64.7 and \\$89.6.\n\nd.  We are 95% confident the price per guest for an Airbnb in Asheville in this sample is between \\$64.7 and \\$89.6.\n\n### Submit\n\n\n\n\n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"100%\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/STA199S24?from=status-bar?\" width=\"100%\"></iframe>\n```\n\n\n\n\n:::\n\n## Leveraging tidymodels tools further\n\nCalculating the observed sample statistic:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_stat_abb <- abb |>\n  specify(response = ppg) |>\n  calculate(stat = \"mean\")  \n```\n:::\n\n\n\n\n\n## Leveraging tidymodels tools further\n\nCalculating the interval:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_95_abb <- boot_dist_abb |>\n  get_confidence_interval(\n    point_estimate = obs_stat_abb, \n    level = 0.95\n  )\n```\n:::\n\n\n\n\n\n## Leveraging tidymodels tools further\n\nVisualizing the interval:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(boot_dist_abb) +\n  shade_confidence_interval(ci_95_abb)\n```\n\n::: {.cell-output-display}\n![](20-bootstrap_files/figure-html/ci-95-abb-viz-1.png){width=576}\n:::\n:::\n\n\n\n\n\n# Application exercise\n\n## Application exercise: `ae-15-duke-forest-bootstrap` {.smaller}\n\n::: appex\n-   Go back to your project called `ae`.\n-   If there are any uncommitted files, commit them, and push.\n-   Work on `ae-15-duke-forest-bootstrap.qmd`.\n:::\n",
    "supporting": [
      "20-bootstrap_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}