{
  "hash": "25bed5f69b457110daaaab747f7f17ae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelling loan interest rates\"\nsubtitle: \"Suggested answers\"\ncategories: \n  - Application exercise\n  - Answers\neditor: visual\n---\n\n\nIn this application exercise we will be studying loan interest rates.\nThe dataset is one you've come across before in your reading -- the dataset about loans from the peer-to-peer lender, Lending Club, from the **openintro** package.\nWe will use **tidyverse** and **tidymodels** for data exploration and modeling, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\n```\n:::\n\n\nBefore we use the dataset, we'll make a few transformations to it.\n\n-   **Your turn:** Review the code below with your neighbor and write a summary of the data transformation pipeline.\n\n*Add response here.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloans <- loans_full_schema |>\n  mutate(\n    credit_util = total_credit_utilized / total_credit_limit,\n    bankruptcy = as.factor(if_else(public_record_bankrupt == 0, 0, 1)),\n    verified_income = droplevels(verified_income),\n    homeownership = str_to_title(homeownership),\n    homeownership = fct_relevel(homeownership, \"Rent\", \"Mortgage\", \"Own\")\n  ) |>\n  rename(credit_checks = inquiries_last_12m) |>\n  select(\n    interest_rate, loan_amount, verified_income, \n    debt_to_income, credit_util, bankruptcy, term, \n    credit_checks, issue_month, homeownership\n  )\n```\n:::\n\n\nHere is a glimpse at the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(loans)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 10\n$ interest_rate   <dbl> 14.07, 12.61, 17.09, 6.72, 14.07, 6.72, 13.59, 11.99, …\n$ loan_amount     <int> 28000, 5000, 2000, 21600, 23000, 5000, 24000, 20000, 2…\n$ verified_income <fct> Verified, Not Verified, Source Verified, Not Verified,…\n$ debt_to_income  <dbl> 18.01, 5.04, 21.15, 10.16, 57.96, 6.46, 23.66, 16.19, …\n$ credit_util     <dbl> 0.54759517, 0.15003472, 0.66134832, 0.19673228, 0.7549…\n$ bankruptcy      <fct> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, …\n$ term            <dbl> 60, 36, 36, 36, 36, 36, 60, 60, 36, 36, 60, 60, 36, 60…\n$ credit_checks   <int> 6, 1, 4, 0, 7, 6, 1, 1, 3, 0, 4, 4, 8, 6, 0, 0, 4, 6, …\n$ issue_month     <fct> Mar-2018, Feb-2018, Feb-2018, Jan-2018, Mar-2018, Jan-…\n$ homeownership   <fct> Mortgage, Rent, Rent, Rent, Rent, Own, Mortgage, Mortg…\n```\n\n\n:::\n:::\n\n\n# Get to know the data\n\n-   **Your turn:** What is a typical interest rate in this dataset?\n    What are some attributes of a typical loan and a typical borrower.\n    Give yourself no more than 5 minutes for this exploration and share 1-2 findings.\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nggplot(loans, aes(x = interest_rate)) +\n  geom_histogram(binwidth = 1)\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-loans-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = loan_amount)) +\n  geom_histogram(binwidth = 5000)\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-loans-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = term)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-loans-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = issue_month)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-loans-4.png){width=672}\n:::\n:::\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nggplot(loans, aes(x = credit_util)) +\n  geom_histogram(binwidth = 0.1)\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = verified_income)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = debt_to_income)) +\n  geom_histogram(binwidth = 10)\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = bankruptcy)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-4.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = credit_checks)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-5.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(loans, aes(x = homeownership)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/explore-borrowers-6.png){width=672}\n:::\n:::\n\n\n# Interest rate vs. credit utilization ratio\n\nThe regression model for interest rate vs. credit utilization is as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_util_fit <- linear_reg() |>\n  fit(interest_rate ~ credit_util, data = loans)\n\ntidy(rate_util_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    10.5     0.0871     121.  0        \n2 credit_util     4.73    0.180       26.3 1.18e-147\n```\n\n\n:::\n:::\n\n\nAnd here is the model visualized:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(loans, aes(x = credit_util, y = interest_rate)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](ae-13-modeling-loans-A_files/figure-html/rate-util-plot-1.png){width=672}\n:::\n:::\n\n\n-   **Your turn:** Interpret the intercept and the slope.\n\nIntercept: Borrowers with 0 credit utilization are predicted, on average, to get an interest rate of 10.5%.\n\nSlope: For each additional point credit utilization is higher, interest rate is predicted to be higher, on average, by 4.73%.\n\n# Interest rate vs. homeownership\n\nNext we predict interest rates from homeownership, which is a categorical predictor with three levels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(loans$homeownership)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Rent\"     \"Mortgage\" \"Own\"     \n```\n\n\n:::\n:::\n\n\n-   **Demo:** Fit the linear regression model to predict interest rate from homeownership and display a tidy summary of the model. Write the estimated model output below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_home_fit <- linear_reg() |>\n  fit(interest_rate ~ homeownership, data = loans)\n\ntidy(rate_home_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term                  estimate std.error statistic  p.value\n  <chr>                    <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)             12.9      0.0803    161.   0       \n2 homeownershipMortgage   -0.866    0.108      -8.03 1.08e-15\n3 homeownershipOwn        -0.611    0.158      -3.88 1.06e- 4\n```\n\n\n:::\n:::\n\n\n-   **Your turn:** Interpret each coefficient in context of the problem.\n\n    -   Intercept: Loan applicants who rent are predicted to receive an interest rate of 12.9%, on average.\n\n    -   Slopes:\n\n        -   The model predicts that loan applicants who have a mortgage for their home receive 0.866% lower interest rate than those who rent their home, on average.\n\n        -   The model predicts that loan applicants who own their home receive 0.611% lower interest rate than those who rent their home, on average.\n\n# Interest rate vs. credit utilization and homeownership\n\n## Main effects model\n\n-   **Demo:** Fit a model to predict interest rate from credit utilization and homeownership, **without** an interaction effect between the two predictors. Display the summary output and write out the estimated regression equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_util_home_fit <- linear_reg() |>\n  fit(interest_rate ~ credit_util + homeownership, data = loans)\n\ntidy(rate_util_home_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)              9.93      0.140    70.8   0        \n2 credit_util              5.34      0.207    25.7   2.20e-141\n3 homeownershipMortgage    0.696     0.121     5.76  8.71e-  9\n4 homeownershipOwn         0.128     0.155     0.827 4.08e-  1\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{interest~rate} = 9.93 + 5.34 \\times credit~util + 0.696 \\times Mortgage + 0.128 \\times Own\n$$\n\n-   **Demo:** Write the estimated regression equation for loan applications from each of the homeownership groups separately.\n    -   Rent: $\\widehat{interest~rate} = 9.93 + 5.34 \\times credit~util$\n    -   Mortgage: $\\widehat{interest~rate} = 10.626 + 5.34 \\times credit~util$\n    -   Own: $\\widehat{interest~rate} = 10.058 + 5.34 \\times credit~util$\n-   **Question:** How does the model predict the interest rate to vary as credit utilization varies for loan applicants with different homeownership status. Are the rates the same or different?\n\nThe same.\n\n## Interaction effects model\n\n-   **Demo:** Fit a model to predict interest rate from credit utilization and homeownership, **with** an interaction effect between the two predictors. Display the summary output and write out the estimated regression equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_util_home_int_fit <- linear_reg() |>\n  fit(interest_rate ~ credit_util * homeownership, data = loans)\n\ntidy(rate_util_home_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term                              estimate std.error statistic  p.value\n  <chr>                                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                          9.44      0.199     47.5  0       \n2 credit_util                          6.20      0.325     19.1  1.01e-79\n3 homeownershipMortgage                1.39      0.228      6.11 1.04e- 9\n4 homeownershipOwn                     0.697     0.316      2.20 2.75e- 2\n5 credit_util:homeownershipMortgage   -1.64      0.457     -3.58 3.49e- 4\n6 credit_util:homeownershipOwn        -1.06      0.590     -1.80 7.24e- 2\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{interest~rate} = 9.44 + 6.20 \\times credit~util + 1.39 \\times Mortgage + 0.697 \\times Own - 1.64 \\times credit_util:Mortgage - 1.06 \\times credit_util:Own\n$$\n\n-   **Demo:** Write the estimated regression equation for loan applications from each of the homeownership groups separately.\n    -   Rent: $\\widehat{interest~rate} = 9.44 + 6.20 \\times credit~util$\n    -   Mortgage: $\\widehat{interest~rate} = 10.83 + 4.56 \\times credit~util$\n    -   Own: $\\widehat{interest~rate} = 10.137 + 5.14 \\times credit~util$\n-   **Question:** How does the model predict the interest rate to vary as credit utilization varies for loan applicants with different homeownership status. Are the rates the same or different?\n\nDifferent.\n\n## Choosing a model\n\nRule of thumb: **Occam's Razor** - Don't overcomplicate the situation!\nWe prefer the *simplest* best model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(rate_util_home_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1    0.0682        0.0679  4.83      244. 1.25e-152     3 -29926. 59861. 59897.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(rate_util_home_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1    0.0694        0.0689  4.83      149. 4.79e-153     5 -29919. 59852. 59903.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n-   **Review:** What is R-squared? What is adjusted R-squared?\n\nR-squared is the percent variability in the response that is explained by our model.\n(Can use when models have same number of variables for model selection)\n\nAdjusted R-squared is similar, but has a penalty for the number of variables in the model.\n(Should use for model selection when models have different numbers of variables).\n\n-   **Question:** Based on the adjusted $R^2$s of these two models, which one do we prefer?\n\nThe interaction effects model, though just barely.\n\n# Another model to consider\n\n-   **Your turn:** Let's add one more model to the variable -- issue month. Should we add this variable to the interaction effects model from earlier?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(interest_rate ~ credit_util * homeownership + issue_month, data = loans) |>\n  glance()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1    0.0694        0.0688  4.83      106. 5.62e-151     7 -29919. 59856. 59921.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nNo, the adjusted R-squared goes down.\n",
    "supporting": [
      "ae-13-modeling-loans-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}